package com.luxsoft.kio

public enum FormaDePago {

	EFECTIVO
	,DEPOSITO
	,TRANSFERENCIA
	,TARJETA_DE_CREDITO
	,TARJETA_DE_DEBITO
	,CHEQUE
	,RECURRENTE
}

//formaDePago inList:['EFECTIVO','DEPOSITO','TRANSFERENCIA','CHEQUE','TARJETA_CREDITO','TARJETA_DEBITO','RECURRENTE']